version: '3.4'

services:
  spacelouncher:
    image: spacelouncher
    build:
      context: .
      target: runner
    command: >
      python debug.py debug
    volumes:
      - /c/Users/root/Documents/GitHub/spacelauncher-parser/app:/app
    ports:
      - 5678:5678
      